title : The Separate Post
tagline: Thoughts on technology, depression, and bullshit.
author :
  name : TheSeparateOne
  email : ifdefnull@lavabit.com
  github : username
  twitter : username
  feedburner : feedname

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md
  
