title : The Separate Post
tagline: Thoughts on bullshit
author :
  name : Jeff Murray
  email : ifdefnull@lavabit.com
  github : username
  twitter : username
  feedburner : feedname

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md
  
